
set(MAIN_EXECUTABLE_NAME ${PROJECT_NAME})

set(OUT_BINARY_DIRECTORY bin)
set(OUT_INTERNAL_DIRECTORY ${OUT_BINARY_DIRECTORY}/internal)
set(OUT_CACHE_DIRECTORY ${OUT_BINARY_DIRECTORY}/cache)

set(OUT_LIBRARY_DIRECTORY lib)

set(OUT_INCLUDE_DIRECTORY include)

set(OUT_RUNTIME_DIRECTORY runtime)
set(OUT_CONFIG_DIRECTORY ${OUT_RUNTIME_DIRECTORY}/config)
set(OUT_SCRIPTS_DIRECTORY ${OUT_RUNTIME_DIRECTORY}/scripts)


set(PROJECT_STRUCTURE_PATHS ${CMAKE_SOURCE_DIR}/resources/internal/paths.yaml.template)

set(PROJECT_STRUCTURE_PATHS_OUTPUT ${CMAKE_BINARY_DIR}/paths.yaml)

configure_file(${PROJECT_STRUCTURE_PATHS} ${PROJECT_STRUCTURE_PATHS_OUTPUT} @ONLY)

install(FILES ${PROJECT_STRUCTURE_PATHS_OUTPUT} DESTINATION ${OUT_INTERNAL_DIRECTORY})