
file(GLOB_RECURSE SRC_FILES_MAIN_EXECUTABLE
    ${SRC_COMPONENT_DIRECTORY}/main/*.c
)

add_executable(${PROJECT_NAME} ${SRC_FILES_MAIN_EXECUTABLE})

target_link_libraries(${PROJECT_NAME} PYTHON klib YAML)

target_include_directories(${PROJECT_NAME} PRIVATE ${SRC_INCLUDE_DIRECTORY})

install(TARGETS ${PROJECT_NAME} DESTINATION ${OUT_BINARY_DIRECTORY})